[package]
name = "rsacpi"
description = "A simple command-line tool to display battery, ac, and thermal information"
version = "0.4.1"
repository = "https://github.com/silverbaum/rsacpi"
license = "MIT"
keywords = ["battery", "CLI"]
categories = ["command-line-utilities"]
edition = "2024"
